#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kazuki Fujita
# SPDX-License-Identifier: BSD-3-Clause

import sys

def factorize(n):
    factors = []
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.append(d)
            n //= d
        d += 1
    if n > 1:
        factors.append(n)
    return factors

def main():
    try:
        line = sys.stdin.read().strip()
        if not line:
            sys.exit(1)
        x = int(line)
    except ValueError:
        sys.exit(1)

    if x < 1:
        sys.exit(1)

    if x == 1:
        print(1)
        sys.exit(0)

    factors = factorize(x)
    print("*".join(str(f) for f in factors))

if __name__ == "__main__":
    main()


