#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kazuki Fujita
# SPDX-License-Identifier: BSD-3-Clause

import sys

def factorize(n):
    factors = []
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.append(d)
            n //= d
        d += 1
    if n > 1:
        factors.append(n)
    return factors

x = int(sys.stdin.read())

factors = factorize(x)

print("*".join(str(f) for f in factors))

